language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
before_install:
- sudo apt install build-essential libpoppler-cpp-dev pkg-config python3-dev
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: vGAi6MqQ8vIjaZAB2i/lwbDz9TdFzTmBTKOGdDwO5rAstjgyjjoKHTPfyZNcSju/lUH9Lli2UULXnfJf2BB86kefWW+WIsRrHJwcl89dvRZVb73/j5EoqWQSMAeztK1QvhK7qxXAvqaMrYeUzNd9k1uJoBkbvOPW6rEB/yE92irXj6RNQjReVWj5Q9SU0RMYPccAGxVL6SQG0V/t3cKCQYTHtzJf0TH8Nt2keUwhx+E0x8FXCkooEKxHq3V6Hkf8twYfeY5u6QGO/IwIE6WqOo939ERWz/EdxqblFKcVsLm84xQwX9LmoNnXpTYrgTPQ546fd/0zYl1MFCbNL1Q7LofbcJouNmJcnrFJO0R7QBjiwWuIbDWlpf1Q3smuuMEztLPiYBicHPuwXeJYd29Nc7g2ldJtCDARn2JbaomBY0DC5P3H4GksuvNP1oxY0b8IkJgbK8Cfn2GuYxLmwx04f3aom75njrV4Ormv38FnxyvIRaQ0ZRmtydsWHMTGBzi5SAr059OxYOVHZHMiUAiKEzBnfvZn5uevdhIQlWFRJcq2rvGoonM3iGCYxOe5BMg4CFI3cx5sAjrYS+/YSmxbXrhMPJU6BKgmEfC0SMDpZoA9x0ke3soA3dMPK3KwmlrKYHyxmzT5hAORSB7zEIsu9seQqH9mA7uzNZNSSB4QrKM=
  on:
    tags: true
    python: 3.8
